# Generated by Django 3.2.18 on 2023-03-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classics', '0003_author_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classics.book'),
        ),
        migrations.AddField(
            model_name='author',
            name='subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classics.subtitle'),
        ),
    ]
