# Generated by Django 3.2.18 on 2023-03-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classics', '0004_auto_20230322_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
