# Generated by Django 3.2.18 on 2023-03-26 12:43

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classics', '0005_auto_20230326_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='title'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='title'),
        ),
    ]
