# Generated by Django 3.2.18 on 2023-03-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classics', '0006_auto_20230326_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
